import{S as u,i as c}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function e(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=e(r);fetch(r.href,o)}})();const m="43264360-d9ed0f3b1b07f2ae565fe2846";function f(s){const e=`https://pixabay.com/api/?${new URLSearchParams({key:m,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(e).then(n=>{if(!n.ok)throw new Error(n.status);return n.json()}).then(n=>n.hits)}const d=document.querySelector(".gallery"),p=new u(".gallery a",{captionsData:"alt"});function h(s){if(s.length==0)c.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const t=s.map(e=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${e.largeImageURL}">
        <img class="photo" src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${e.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${e.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${e.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${e.downloads}</p></li>
        </ul>
        </li>`).join("");d.insertAdjacentHTML("beforeend",t),p.refresh()}}const g=document.querySelector(".gallery"),y=document.querySelector("input"),L=document.querySelector("form"),l=document.querySelector(".loader");function b(){l.classList.remove("is-hidden")}function w(){l.classList.add("is-hidden")}function a(s,t="error"){c[t]({message:s,position:"topRight"})}function S(s){s.preventDefault();const t=y.value.trim();if(t===""){a("Please fill in the field for search","error");return}b(),f(t).then(e=>h(e)).catch(e=>{console.log(e),a("❌ Sorry, there are no images matching your search query. Please, try again!","error")}).finally(()=>w()),g.innerHTML=""}L.addEventListener("submit",S);
//# sourceMappingURL=commonHelpers.js.map
