import{i as l,S as m}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function t(e){if(e.ep)return;e.ep=!0;const n=s(e);fetch(e.href,n)}})();const f=document.querySelector("input");f.value.trim();function d(r){const s=`https://pixabay.com/api/?${new URLSearchParams({key:"43264360-d9ed0f3b1b07f2ae565fe2846",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(s).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const p=document.querySelector(".gallery");function h(r){if(r.length==0)l.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const o=r.map(t=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${t.largeImageURL}">
        <img class="photo" src="${t.webformatURL}" alt="${t.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${t.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${t.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${t.downloads}</p></li>
        </ul>
        </li>`).join("");p.insertAdjacentHTML("beforeend",o),new m(".gallery a",{captionsData:"alt"}).refresh()}}const g=document.querySelector(".gallery"),a=document.querySelector("input"),y=document.querySelector("form"),u=document.querySelector(".loader");function L(){u.classList.remove("is-hidden")}function b(){u.classList.add("is-hidden")}function c(r,o="error"){l[o]({message:r,position:"topRight"})}function S(r){r.preventDefault();const o=a.value.trim();if(o===""){c("Please fill in the field for search","error");return}L(),d(o).then(s=>h(s.hits)).catch(s=>{console.log(s),c("❌ Sorry, there are no images matching your search query. Please, try again!","error")}).finally(()=>b()),g.innerHTML=""}function w(r){r.preventDefault(),a.value=r.target.value.trim()}y.addEventListener("submit",S);a.addEventListener("input",w);
//# sourceMappingURL=commonHelpers.js.map
